services:
  pythonapp:
    build: web/
    command: sh -c "sleep 15s ;python3 ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mydb
    links:
      - mydb
    ports:
      - '8000:8000'
    expose:
      - '8000'

  mydb:
      build: ./mysql/
      restart: always
      container_name: mydb
      environment:
        MYSQL_DATABASE: 'devblog'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'

